build:
  image: docker:20.10.16
  stage: build
  services:
    - docker:20.10.16-dind
  script:
    - echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_LOGIN --password-stdin https://index.docker.io/v1/
    - docker build -t $DOCKER_NAME .
    - docker push $DOCKER_NAME